/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface-container-low": "#1b1c1c",
        "secondary-fixed-dim": "#e6c183",
        "on-primary-fixed": "#131e16",
        "surface-tint": "#bdcabe",
        "surface-dim": "#131313",
        "on-secondary": "#422d00",
        "on-primary": "#28332b",
        "surface-container-high": "#2a2a2a",
        "background": "#131313",
        "secondary-container": "#5e4513",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#556157",
        "tertiary-fixed-dim": "#b6ccb5",
        "on-tertiary-fixed": "#0e1f10",
        "on-error-container": "#ffdad6",
        "primary": "#bdcabe",
        "tertiary-container": "#152717",
        "secondary": "var(--color-secondary, #e6c183)",
        "surface-variant": "#353535",
        "on-tertiary": "#223524",
        "outline-variant": "#434843",
        "on-secondary-fixed-variant": "#5b4311",
        "on-surface-variant": "#c4c8c2",
        "surface-container-highest": "#353535",
        "surface-bright": "#393939",
        "primary-fixed": "#d9e6d9",
        "on-error": "#690005",
        "surface": "#131313",
        "secondary-fixed": "#ffdea8",
        "primary-container": "#1b261e",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#3e4a40",
        "tertiary": "#b6ccb5",
        "on-surface": "#e5e2e1",
        "inverse-on-surface": "#303030",
        "on-primary-container": "#818e83",
        "on-secondary-fixed": "#271900",
        "tertiary-fixed": "#d2e9d0",
        "on-tertiary-fixed-variant": "#384b39",
        "on-secondary-container": "#d7b377",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#7b907a",
        "surface-container-lowest": "#0e0e0e",
        "outline": "#8d928c",
        "surface-container": "#1f2020",
        "primary-fixed-dim": "#bdcabe"
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      spacing: { "gutter": "24px", "margin-page": "40px", "unit": "8px", "section-gap": "80px" },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "h3": ["Newsreader", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "h1": ["Newsreader", "serif"],
        "h2": ["Newsreader", "serif"],
        "newsreader": ["Newsreader", "serif"],
        "sans": ["DM Sans", "sans-serif"],
        "serif": ["Lora", "serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "300" }],
        "h2": ["32px", { lineHeight: "1.3", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
