
const SUPABASE_URL = 'https://aogfbetxmzsjjdhbured.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZ2ZiZXR4bXpzampkaGJ1cmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MTQyNDgsImV4cCI6MjA4OTA5MDI0OH0.OedI5IJQuUT-qB4INo2EH2yALrkoF3xqRMviMi9ESnM';

const projectName = "WEB-DEV-MASTERY";
const userEmail = "MOHIT@EXAMPLE.COM"; // Need to confirm this or fetch it.

const tasks = [
  "🧱 Phase 1 — The Basics",
  "How the Web Works",
  "HTTP / HTTPS",
  "DNS & domains",
  "Request / Response cycle",
  "Browsers & rendering",
  "Status codes",
  "Cookies & sessions",
  "REST principles",
  "HTTP/2 & HTTP/3",
  "WebSockets",
  "Command Line & Git",
  "Bash basics",
  "Git init / clone / add",
  "Commit / push / pull",
  "Branching & merging",
  "GitHub / GitLab",
  "Rebasing",
  "Git hooks",
  "Monorepo strategies",
  "HTML",
  "Document structure",
  "Semantic elements",
  "Forms & inputs",
  "Tables",
  "Links & images",
  "Meta tags & SEO",
  "Accessibility (a11y)",
  "HTML5 APIs",
  "Canvas element",
  "Web components",
  "CSS",
  "Selectors & specificity",
  "Box model",
  "Flexbox",
  "CSS Grid",
  "Responsive design",
  "Media queries",
  "Transitions & animations",
  "CSS variables",
  "Pseudo-elements",
  "CSS architecture (BEM)",
  "Custom properties",
  "⚡ Phase 2 — JavaScript",
  "Core Language",
  "Variables (let / const / var)",
  "Data types & coercion",
  "Functions & closures",
  "Arrays & objects",
  "Destructuring",
  "Spread / rest",
  "Template literals",
  "Modules (ESM)",
  "Error handling",
  "Prototype chain",
  "Symbol & WeakMap",
  "Proxy & Reflect",
  "Generators & iterators",
  "Async JavaScript",
  "Callbacks",
  "Promises",
  "Async / Await",
  "Fetch API",
  "Event loop",
  "Microtask queue",
  "Promise.all / race / any",
  "AbortController",
  "Async generators",
  "TypeScript",
  "Types & interfaces",
  "Generics",
  "Type narrowing",
  "Enums & unions",
  "Utility types",
  "tsconfig.json",
  "Conditional types",
  "Mapped types",
  "Template literal types",
  "Decorators",
  "Build Tools",
  "npm / pnpm / yarn",
  "Vite",
  "Webpack",
  "Rollup",
  "esbuild",
  "Tree shaking",
  "Code splitting",
  "Custom plugins",
  "Module federation",
  "🎨 Phase 3 — Frontend",
  "React (Core Framework)",
  "JSX & components",
  "Props & state",
  "useState, useEffect hooks",
  "Context API",
  "useMemo / useCallback",
  "Custom hooks",
  "React 19 features",
  "Other Frameworks (pick one)",
  "Vue.js",
  "Angular",
  "Svelte",
  "SolidJS",
  "Qwik",
  "CSS Tooling & Design",
  "Tailwind CSS",
  "CSS Modules",
  "Sass / SCSS",
  "Styled Components",
  "Shadcn UI",
  "Radix UI",
  "Headless UI",
  "Design tokens",
  "Dark mode patterns",
  "CSS-in-JS",
  "Vanilla Extract",
  "State Management",
  "Redux Toolkit",
  "Zustand",
  "Jotai",
  "Recoil",
  "TanStack Query",
  "Client vs server state",
  "Optimistic updates",
  "XState (state machines)",
  "Routing & Meta-frameworks",
  "React Router v6",
  "Next.js (App Router)",
  "Nuxt.js",
  "Remix",
  "Astro",
  "SSR vs SSG vs CSR",
  "ISR (Incremental Static Regeneration)",
  "Edge rendering",
  "Streaming & Suspense",
  "Frontend Testing",
  "Vitest",
  "Jest",
  "React Testing Library",
  "Playwright",
  "Cypress",
  "Unit testing",
  "Integration testing",
  "E2E testing",
  "Visual regression (Storybook)",
  "Frontend Performance",
  "Core Web Vitals",
  "Lazy loading",
  "Image optimization",
  "Lighthouse",
  "Bundle analysis",
  "Web workers",
  "Virtual scrolling",
  "🔧 Phase 4 — Backend",
  "Node.js Runtime",
  "Node.js core modules",
  "File system (fs)",
  "Streams",
  "Event emitters",
  "Child processes",
  "Cluster mode",
  "Worker threads",
  "Backend Frameworks",
  "Express.js",
  "Fastify",
  "NestJS",
  "Hono",
  "API Design",
  "RESTful API design",
  "HTTP methods & status codes",
  "Request validation",
  "Error handling patterns",
  "Pagination",
  "API versioning",
  "Rate limiting",
  "GraphQL",
  "tRPC",
  "gRPC",
  "WebSockets / SSE",
  "OpenAPI / Swagger",
  "Auth & Security",
  "JWT tokens",
  "Sessions & cookies",
  "OAuth 2.0",
  "Password hashing (bcrypt)",
  "CORS",
  "HTTPS / TLS",
  "Passport.js",
  "Auth0 / Clerk / NextAuth",
  "RBAC / ABAC",
  "CSRF protection",
  "OWASP Top 10",
  "Other Backend Skills",
  "Middleware pattern",
  "File uploads (Multer)",
  "Email (Nodemailer / Resend)",
  "Cron jobs",
  "BullMQ (job queues)",
  "Zod / Joi (validation)",
  "MVC pattern",
  "Microservices architecture",
  "Event-driven architecture",
  "Message brokers (Kafka, RabbitMQ)",
  "Other Languages (optional, pick one)",
  "Python — Django / FastAPI",
  "Go — Gin / Fiber",
  "PHP — Laravel",
  "Rust — Actix / Axum",
  "Java — Spring Boot",
  "Elixir — Phoenix",
  "🗄️ Phase 5 — Databases",
  "Relational (SQL)",
  "SQL fundamentals",
  "CRUD operations",
  "Joins (INNER, LEFT, RIGHT, FULL)",
  "Indexes & performance",
  "Transactions (ACID)",
  "Normalization",
  "Window functions",
  "Stored procedures",
  "Query explain / analyze",
  "Partitioning & sharding",
  "SQL Databases",
  "PostgreSQL",
  "MySQL / MariaDB",
  "SQLite",
  "NoSQL",
  "Document stores",
  "Key-value stores",
  "Time-series databases",
  "MongoDB",
  "Redis (caching & pub/sub)",
  "DynamoDB",
  "Firestore",
  "Cassandra",
  "CAP theorem",
  "Eventual consistency",
  "ORMs & Query Builders",
  "Prisma",
  "Drizzle ORM",
  "TypeORM",
  "Sequelize",
  "Knex.js",
  "N+1 problem",
  "Migrations",
  "Seeding data",
  "Connection pooling",
  "Caching & Search",
  "Cache invalidation strategies",
  "TTL strategies",
  "Full-text search",
  "Elasticsearch",
  "Algolia",
  "Meilisearch",
  "Vector databases (pgvector)",
  "🚀 Phase 6 — DevOps & Deployment",
  "Containers",
  "Docker",
  "Dockerfile authoring",
  "Docker Compose",
  "Container registries",
  "Image layers & caching",
  "Kubernetes basics",
  "Helm charts",
  "Service mesh",
  "Hosting & Cloud",
  "Vercel",
  "Netlify",
  "Railway",
  "Render",
  "AWS (EC2, S3, Lambda)",
  "Google Cloud",
  "Azure",
  "Cloudflare Workers",
  "Auto-scaling",
  "Kubernetes (advanced)",
  "CI/CD Pipelines",
  "GitHub Actions",
  "GitLab CI",
  "CircleCI",
  "Jenkins",
  "Automated testing in pipelines",
  "Staged deployments",
  "Blue/green deployments",
  "Feature flags",
  "Canary releases",
  "Monitoring & Observability",
  "Structured logging",
  "Sentry (error tracking)",
  "Datadog",
  "Grafana",
  "Prometheus",
  "New Relic",
  "Alerting",
  "OpenTelemetry",
  "Distributed tracing",
  "🧠 Phase 7 — Advanced Topics",
  "System Design",
  "Load balancing",
  "CDN & edge computing",
  "Database replication",
  "Message queues",
  "API gateways",
  "Horizontal scaling",
  "Service discovery",
  "SLA / SLO / SLI",
  "Web Security (Advanced)",
  "XSS prevention",
  "SQL injection",
  "CSRF tokens",
  "Content Security Policy (CSP)",
  "Secure headers",
  "Dependency auditing",
  "Penetration testing basics",
  "Zero-trust model",
  "Architecture Patterns",
  "SOLID principles",
  "Domain-Driven Design (DDD)",
  "CQRS pattern",
  "Event sourcing",
  "Hexagonal architecture",
  "Serverless patterns",
  "Micro-frontends",
  "Clean code principles",
  "Dependency injection",
  "AI Integration",
  "LLM APIs (OpenAI, Claude)",
  "Prompt engineering",
  "RAG pipelines",
  "Vector embeddings",
  "LangChain / LlamaIndex",
  "Vercel AI SDK",
  "Streaming AI responses",
  "Function / tool calling",
  "🛠️ Phase 8 — Professional Toolkit",
  "Editors",
  "VS Code (extensions, shortcuts)",
  "WebStorm",
  "Neovim",
  "Zed",
  "Cursor (AI editor)",
  "Debugger usage",
  "Developer Tools",
  "Chrome DevTools",
  "Postman / Insomnia",
  "Hoppscotch",
  "ESLint",
  "Prettier",
  "Husky (git hooks)",
  "Commitlint",
  "Storybook",
  "Turborepo",
  "Design & Collaboration",
  "Figma",
  "Excalidraw",
  "Design handoff workflows",
  "Notion / Confluence",
  "Linear / Jira",
  "Agile / Scrum",
  "Code review best practices",
  "AI Dev Tools",
  "GitHub Copilot",
  "Claude Code",
  "Cursor AI",
  "Windsurf",
  "v0 by Vercel",
  "AI-assisted code review",
  "AI test generation"
];

async function run() {
  console.log("Fetching project ID...");
  const pRes = await fetch(`${SUPABASE_URL}/rest/v1/projects`, {
    headers: {
      'apikey': SUPABASE_ANON_KEY,
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
    }
  });
  const projects = await pRes.json();
  
  const project = projects.find(p => p.title.toUpperCase() === projectName.toUpperCase());
  
  if (!project) {
    console.error("Project not found! Available projects:", projects.map(p => p.title));
    process.exit(1);
  }
  
  const projectId = project.id;
  const actualUserEmail = project.user_email;
  
  console.log(`Found project: ${projectName} (ID: ${projectId}) for ${actualUserEmail}`);
  
  const payload = tasks.map(t => ({
    text: t,
    completed: false,
    user_email: actualUserEmail,
    project_id: projectId,
    cat: 'project'
  }));
  
  console.log(`Inserting ${payload.length} tasks...`);
  const iRes = await fetch(`${SUPABASE_URL}/rest/v1/tasks`, {
    method: 'POST',
    headers: {
      'apikey': SUPABASE_ANON_KEY,
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=minimal'
    },
    body: JSON.stringify(payload)
  });
  
  if (iRes.ok) {
    console.log("Tasks inserted successfully!");
  } else {
    const err = await iRes.text();
    console.error("Failed to insert tasks:", err);
  }
}

run();
